# Generated by Django 5.0.7 on 2024-11-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_nasko', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_nasko',
            name='feces_mixture',
            field=models.TextField(blank=True, null=True, verbose_name='Замечания'),
        ),
        migrations.AlterField(
            model_name='monitoring_nasko',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
    ]
