# Generated by Django 5.0.7 on 2024-11-09 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0017_alter_organization_consultant_and_more'),
        ('user_app', '0014_personalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitAuditMilk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата мониторинга')),
                ('content', models.CharField(max_length=100, verbose_name='Тип содержания')),
                ('livestock', models.IntegerField(max_length=100, verbose_name='Поголовье на ферме')),
                ('dairy_cattle', models.IntegerField(max_length=100, verbose_name='Дойное поголовье')),
                ('days_lactation', models.IntegerField(max_length=100, verbose_name='Среднее количество дней лактации')),
                ('milk', models.IntegerField(max_length=100, verbose_name='Общий удой по ферме')),
                ('milk_cow', models.IntegerField(max_length=100, verbose_name='Удой на одну корову в сутки, кг')),
                ('milk_sales', models.IntegerField(max_length=100, verbose_name='Реализация молока в день')),
                ('milk_fat', models.FloatField(max_length=100, verbose_name='Жирность молока, %')),
                ('milk_protein', models.FloatField(max_length=100, verbose_name='Белок молока, %')),
                ('milk_somatics', models.IntegerField(max_length=100, verbose_name='Соматика молока, тыс/мл')),
                ('number_milkings', models.CharField(max_length=100, verbose_name='Количество доений')),
                ('weight_cow', models.CharField(max_length=100, verbose_name='Вес взрослого животного')),
                ('number_calvings', models.CharField(max_length=100, verbose_name='Количество отелов за месяц')),
                ('calf_weight', models.CharField(max_length=100, verbose_name='Вес телят при рождении')),
                ('groups', models.TextField(blank=True, max_length=1000, verbose_name='Разделение по группам')),
                ('diet_composition', models.TextField(blank=True, max_length=1000, verbose_name='Состав рациона')),
                ('diet_composition_feed', models.TextField(blank=True, max_length=1000, verbose_name='Состав комбикорма')),
                ('notes_diet', models.TextField(blank=True, max_length=4000, verbose_name='Замечания по рациону')),
                ('notes_animall', models.TextField(blank=True, max_length=4000, verbose_name='Замечания по животным')),
                ('withdrawal', models.TextField(blank=True, max_length=1000, verbose_name='Выбытие(количество, причины)')),
                ('notes', models.TextField(blank=True, max_length=4000, verbose_name='Другие проблемы')),
                ('offers', models.TextField(blank=True, max_length=4000, verbose_name='Предложения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('user_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.job', verbose_name='Должность специалиста')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitauditmilks', to='consultants.organization', verbose_name='Организация')),
            ],
        ),
    ]
