# Generated by Django 5.0.7 on 2024-11-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitauditmilk',
            name='calf_weight',
            field=models.IntegerField(verbose_name='Вес телят при рождении'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='dairy_cattle',
            field=models.IntegerField(verbose_name='Дойное поголовье'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='days_lactation',
            field=models.IntegerField(verbose_name='Среднее количество дней лактации'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='livestock',
            field=models.IntegerField(verbose_name='Поголовье на ферме'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='milk',
            field=models.IntegerField(verbose_name='Общий удой по ферме'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='milk_cow',
            field=models.IntegerField(verbose_name='Удой на одну корову в сутки, кг'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='milk_fat',
            field=models.FloatField(verbose_name='Жирность молока, %'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='milk_protein',
            field=models.FloatField(verbose_name='Белок молока, %'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='milk_sales',
            field=models.IntegerField(verbose_name='Реализация молока в день'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='milk_somatics',
            field=models.IntegerField(verbose_name='Соматика молока, тыс/мл'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='number_calvings',
            field=models.IntegerField(verbose_name='Количество отелов за месяц'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='number_milkings',
            field=models.IntegerField(verbose_name='Количество доений'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='weight_cow',
            field=models.IntegerField(verbose_name='Вес взрослого животного'),
        ),
    ]
