# Generated by Django 5.0.7 on 2024-11-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_audit', '0002_alter_monitauditmilk_calf_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitauditmilk',
            name='dairy_cattle',
            field=models.IntegerField(verbose_name='Количество дойного поголовья (коров с первотелками)'),
        ),
    ]
