# Generated by Django 5.0.7 on 2024-11-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_audit', '0003_alter_monitauditmilk_dairy_cattle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitauditmilk',
            name='dairy_cattle',
            field=models.IntegerField(verbose_name='Количество дойного поголовья'),
        ),
    ]
