# Generated by Django 5.0.7 on 2024-11-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_audit', '0004_alter_monitauditmilk_dairy_cattle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitauditmilk',
            name='milk_cow',
            field=models.FloatField(verbose_name='Удой на одну корову в сутки, кг'),
        ),
    ]
