# Generated by Django 5.0.7 on 2024-11-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_audit', '0006_alter_monitauditmilk_diet_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitauditmilk',
            name='offers_1',
            field=models.TextField(blank=True, verbose_name='Предложения по сортировке стада'),
        ),
        migrations.AddField(
            model_name='monitauditmilk',
            name='offers_2',
            field=models.TextField(blank=True, verbose_name='Предложения по комбикорму'),
        ),
        migrations.AddField(
            model_name='monitauditmilk',
            name='offers_3',
            field=models.TextField(blank=True, verbose_name='Предложения'),
        ),
        migrations.AddField(
            model_name='monitauditmilk',
            name='offers_4',
            field=models.TextField(blank=True, verbose_name='Предложения'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='diet_composition',
            field=models.TextField(blank=True, verbose_name='Состав рациона'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='diet_composition_feed',
            field=models.TextField(blank=True, verbose_name='Состав комбикорма'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='groups',
            field=models.TextField(blank=True, verbose_name='Разделение по группам'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Другие проблемы'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='notes_animall',
            field=models.TextField(blank=True, verbose_name='Замечания по животным'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='notes_diet',
            field=models.TextField(blank=True, verbose_name='Предложения по рациону'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='offers',
            field=models.TextField(blank=True, verbose_name='Предложения и предстоящий план работы'),
        ),
        migrations.AlterField(
            model_name='monitauditmilk',
            name='withdrawal',
            field=models.TextField(blank=True, verbose_name='Выбытие(количество, причины)'),
        ),
    ]
