# Generated by Django 5.0.7 on 2024-10-29 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0012_profile_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
