# Generated by Django 5.0.7 on 2024-11-09 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0014_personalaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Должность'),
        ),
    ]
