# Generated by Django 5.0.7 on 2024-11-06 17:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0016_delete_monitoring'),
        ('user_app', '0014_personalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring_ket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата мониторинга')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='Группа животных')),
                ('animal_1', models.IntegerField(blank=True, null=True, verbose_name='Номер 1 животного')),
                ('animal_2', models.IntegerField(blank=True, null=True, verbose_name='Номер 2 животного')),
                ('animal_3', models.IntegerField(blank=True, null=True, verbose_name='Номер 3 животного')),
                ('animal_4', models.IntegerField(blank=True, null=True, verbose_name='Номер 4 животного')),
                ('animal_5', models.IntegerField(blank=True, null=True, verbose_name='Номер 5 животного')),
                ('animal_6', models.IntegerField(blank=True, null=True, verbose_name='Номер 6 животного')),
                ('animal_7', models.IntegerField(blank=True, null=True, verbose_name='Номер 7 животного')),
                ('animal_8', models.IntegerField(blank=True, null=True, verbose_name='Номер 8 животного')),
                ('animal_9', models.IntegerField(blank=True, null=True, verbose_name='Номер 9 животного')),
                ('animal_10', models.IntegerField(blank=True, null=True, verbose_name='Номер 10 животного')),
                ('animal_11', models.IntegerField(blank=True, null=True, verbose_name='Номер 11 животного')),
                ('animal_12', models.IntegerField(blank=True, null=True, verbose_name='Номер 12 животного')),
                ('animal_13', models.IntegerField(blank=True, null=True, verbose_name='Номер 13 животного')),
                ('animal_14', models.IntegerField(blank=True, null=True, verbose_name='Номер 14 животного')),
                ('animal_15', models.IntegerField(blank=True, null=True, verbose_name='Номер 15 животного')),
                ('keton_1', models.FloatField(blank=True, null=True, verbose_name='Кетоны 1 животного')),
                ('keton_2', models.FloatField(blank=True, null=True, verbose_name='Кетоны 2 животного')),
                ('keton_3', models.FloatField(blank=True, null=True, verbose_name='Кетоны 3 животного')),
                ('keton_4', models.FloatField(blank=True, null=True, verbose_name='Кетоны 4 животного')),
                ('keton_5', models.FloatField(blank=True, null=True, verbose_name='Кетоны 5 животного')),
                ('keton_6', models.FloatField(blank=True, null=True, verbose_name='Кетоны 6 животного')),
                ('keton_7', models.FloatField(blank=True, null=True, verbose_name='Кетоны 7 животного')),
                ('keton_8', models.FloatField(blank=True, null=True, verbose_name='Кетоны 8 животного')),
                ('keton_9', models.FloatField(blank=True, null=True, verbose_name='Кетоны 9 животного')),
                ('keton_10', models.FloatField(blank=True, null=True, verbose_name='Кетоны 10 животного')),
                ('keton_11', models.FloatField(blank=True, null=True, verbose_name='Кетоны 11 животного')),
                ('keton_12', models.FloatField(blank=True, null=True, verbose_name='Кетоны 12 животного')),
                ('keton_13', models.FloatField(blank=True, null=True, verbose_name='Кетоны 13 животного')),
                ('keton_14', models.FloatField(blank=True, null=True, verbose_name='Кетоны 14 животного')),
                ('keton_15', models.FloatField(blank=True, null=True, verbose_name='Кетоны 15 животного')),
                ('recommendations', models.TextField(max_length=4000, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('user_name', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_app.job', verbose_name='Должность специалиста')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_kets', to='consultants.organization', verbose_name='Организация')),
            ],
        ),
    ]
