# Generated by Django 5.0.7 on 2024-10-30 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0002_manager_alter_organization_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_organizations', to='consultants.manager', verbose_name='Менеджер'),
        ),
    ]
