# Generated by Django 5.0.7 on 2024-10-30 17:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0004_alter_organization_consultant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultant',
            name='user',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='user',
        ),
        migrations.AddField(
            model_name='consultant',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
