# Generated by Django 5.0.7 on 2024-10-30 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0006_alter_organization_manager_remove_consultant_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
