# Generated by Django 5.0.7 on 2024-10-30 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0008_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='manager',
        ),
        migrations.DeleteModel(
            name='Consultant',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
