# Generated by Django 5.0.7 on 2024-11-06 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0014_alter_organization_manager'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
