# Generated by Django 5.0.7 on 2024-11-06 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0015_monitoring'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monitoring',
        ),
    ]
