# Generated by Django 5.0.7 on 2024-11-06 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0016_delete_monitoring'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='consultants.consultant', verbose_name='Консультант'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_organizations', to=settings.AUTH_USER_MODEL),
        ),
    ]
