# Generated by Django 5.0.7 on 2024-11-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0017_alter_organization_consultant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='You',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
