# Generated by Django 5.0.7 on 2024-11-10 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0018_you'),
    ]

    operations = [
        migrations.DeleteModel(
            name='You',
        ),
    ]
