# Generated by Django 5.0.7 on 2024-12-21 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0019_delete_you'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='farm',
            field=models.CharField(max_length=200, verbose_name='Название фермы(комплекса)'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Выбор менеджера данной организации'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название организации'),
        ),
    ]
