# Generated by Django 5.0.7 on 2024-11-06 05:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0014_alter_organization_manager'),
        ('user_app', '0014_personalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monitoring_ph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата мониторинга')),
                ('group', models.CharField(max_length=100, null=True, verbose_name='Группа животных')),
                ('animal_1', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_2', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_3', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_4', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_5', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_6', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_7', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_8', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_9', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('animal_10', models.IntegerField(blank=True, null=True, verbose_name='Номер животного')),
                ('ph_1', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_2', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_3', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_4', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_5', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_6', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_7', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_8', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_9', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('ph_10', models.FloatField(blank=True, null=True, verbose_name='ph животного')),
                ('recommendations', models.TextField(max_length=4000, null=True, verbose_name='Рекомендации')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('user_name', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_app.job', verbose_name='Должность специалиста')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_ph', to='consultants.organization', verbose_name='Организация')),
            ],
        ),
    ]
