# Generated by Django 5.0.7 on 2024-11-06 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultants', '0014_alter_organization_manager'),
        ('monitoring_ph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_ph',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoring_phs', to='consultants.organization', verbose_name='Организация'),
        ),
    ]
