# Generated by Django 5.0.7 on 2024-11-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_ph', '0002_alter_monitoring_ph_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 1 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_10',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 10 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_2',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 2 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_3',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 3 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_4',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 4 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_5',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 5 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_6',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 6 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_7',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 7 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_8',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 8 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='animal_9',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер 9 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_1',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 1 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_10',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 10 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_2',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 2 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_3',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 3 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_4',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 4 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_5',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 5 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_6',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 6 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_7',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 7 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_8',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 8 животного'),
        ),
        migrations.AlterField(
            model_name='monitoring_ph',
            name='ph_9',
            field=models.FloatField(blank=True, null=True, verbose_name='ph 9 животного'),
        ),
    ]
