# Generated by Django 5.0.7 on 2024-11-06 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_ph', '0003_alter_monitoring_ph_animal_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoring_ph',
            name='recommendations',
            field=models.TextField(blank=True, max_length=4000, null=True, verbose_name='Рекомендации'),
        ),
    ]
