# Generated by Django 5.0.7 on 2025-01-12 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_ph', '0005_alter_monitoring_ph_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_1',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_10',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_2',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_3',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_4',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_5',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_6',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_7',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_8',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
        migrations.AddField(
            model_name='monitoring_ph',
            name='calving_9',
            field=models.CharField(max_length=30, null=True, verbose_name='Дата перевода в сухостой-2'),
        ),
    ]
