# Generated by Django 5.0.7 on 2024-11-11 16:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0019_delete_you'),
        ('user_app', '0015_alter_job_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitAuditCalves',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата мониторинга')),
                ('content', models.CharField(max_length=100, verbose_name='Тип содержания')),
                ('livestock_calves', models.IntegerField(verbose_name='Количество телят в группе мониторинга ')),
                ('weight_calves', models.IntegerField(verbose_name='Средний вес телят')),
                ('number_boxes', models.IntegerField(verbose_name='Количество боксов для телят')),
                ('number_calf', models.IntegerField(verbose_name='Количество телят 0-2 мес')),
                ('number_milk', models.IntegerField(verbose_name='Количество поений молоком в сутки')),
                ('calf_weight', models.IntegerField(verbose_name='Вес телят при рождении')),
                ('groups', models.TextField(blank=True, max_length=1000, verbose_name='Разделение по группам')),
                ('diet_composition', models.TextField(blank=True, max_length=1000, verbose_name='Состав рациона')),
                ('diet_composition_feed', models.TextField(blank=True, max_length=1000, verbose_name='Состав комбикорма')),
                ('notes_diet', models.TextField(blank=True, max_length=4000, verbose_name='Замечания по рациону')),
                ('notes_animall', models.TextField(blank=True, max_length=4000, verbose_name='Замечания по телятам')),
                ('withdrawal', models.TextField(blank=True, max_length=1000, verbose_name='Выбытие(количество, причины)')),
                ('notes', models.TextField(blank=True, max_length=4000, verbose_name='Другие проблемы')),
                ('offers', models.TextField(blank=True, max_length=4000, verbose_name='Предложения')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('user_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_app.job', verbose_name='Должность специалиста')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitauditcalvess', to='consultants.organization', verbose_name='Организация')),
            ],
        ),
    ]
