# Generated by Django 5.0.7 on 2024-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_calves', '0002_monitauditcalves_number_calvings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitauditcalves',
            name='number_calvings',
            field=models.IntegerField(verbose_name='Количество отелов за месяц'),
        ),
    ]
