# Generated by Django 5.0.7 on 2024-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_calves', '0003_alter_monitauditcalves_number_calvings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitauditcalves',
            name='calf_weight',
            field=models.IntegerField(null=True, verbose_name='Вес телят при рождении'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='number_calvings',
            field=models.IntegerField(null=True, verbose_name='Количество отелов за месяц'),
        ),
    ]
