# Generated by Django 5.0.7 on 2024-11-19 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_calves', '0006_alter_monitauditcalves_diet_composition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitauditcalves',
            name='offers_1',
            field=models.TextField(blank=True, verbose_name='Предложения по сортировке телят'),
        ),
        migrations.AddField(
            model_name='monitauditcalves',
            name='offers_2',
            field=models.TextField(blank=True, verbose_name='Предложения по комбикорму'),
        ),
        migrations.AddField(
            model_name='monitauditcalves',
            name='offers_3',
            field=models.TextField(blank=True, verbose_name='Предложения'),
        ),
        migrations.AddField(
            model_name='monitauditcalves',
            name='offers_4',
            field=models.TextField(blank=True, verbose_name='Предложения'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='diet_composition',
            field=models.TextField(blank=True, verbose_name='Состав рациона'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='diet_composition_feed',
            field=models.TextField(blank=True, verbose_name='Состав комбикорма'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='groups',
            field=models.TextField(blank=True, verbose_name='Разделение по группам'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Другие проблемы'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='notes_animall',
            field=models.TextField(blank=True, verbose_name='Замечания по телятам'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='notes_diet',
            field=models.TextField(blank=True, verbose_name='Предложения по рациону'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='offers',
            field=models.TextField(blank=True, verbose_name='Предложения и предстоящий план работы'),
        ),
        migrations.AlterField(
            model_name='monitauditcalves',
            name='withdrawal',
            field=models.TextField(blank=True, verbose_name='Выбытие (количество, причины)'),
        ),
    ]
