# Generated by Django 5.0.7 on 2025-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_calves', '0007_monitauditcalves_offers_1_monitauditcalves_offers_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitauditcalves',
            name='weight_calves',
            field=models.IntegerField(verbose_name='Среднесуточный привес, гр.'),
        ),
    ]
