# Generated by Django 5.0.7 on 2025-01-01 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_remains', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remain',
            name='products',
        ),
        migrations.AddField(
            model_name='remain',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Коментарии'),
        ),
        migrations.AddField(
            model_name='remain',
            name='dose_products_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза 1 продукта'),
        ),
        migrations.AddField(
            model_name='remain',
            name='dose_products_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза 2 продукта'),
        ),
        migrations.AddField(
            model_name='remain',
            name='dose_products_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза 3 продукта'),
        ),
        migrations.AddField(
            model_name='remain',
            name='dose_products_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза 4 продукта'),
        ),
        migrations.AddField(
            model_name='remain',
            name='dose_products_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза 5 продукта'),
        ),
        migrations.AddField(
            model_name='remain',
            name='number_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов или тонн на "1" продукт'),
        ),
        migrations.AddField(
            model_name='remain',
            name='number_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов или тонн на "2" продукт'),
        ),
        migrations.AddField(
            model_name='remain',
            name='number_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов или тонн на "3" продукт'),
        ),
        migrations.AddField(
            model_name='remain',
            name='number_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов или тонн на "4" продукт'),
        ),
        migrations.AddField(
            model_name='remain',
            name='number_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов или тонн на "5" продукт'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продукт 1'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продукт 2'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продукт 3'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продукт 4'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Продукт 5'),
        ),
    ]
