# Generated by Django 5.0.7 on 2025-01-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_remains', '0002_remove_remain_products_remain_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remain',
            name='products_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 1'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 2'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 3'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 4'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_5',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 5'),
        ),
    ]
