# Generated by Django 5.0.7 on 2025-01-01 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_remains', '0003_alter_remain_products_1_alter_remain_products_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remain',
            name='products_name_1',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Продукт 1'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_name_2',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Продукт 2'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_name_3',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Продукт 3'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_name_4',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Продукт 4'),
        ),
        migrations.AddField(
            model_name='remain',
            name='products_name_5',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Продукт 5'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 1'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 2'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 3'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 4'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 5'),
        ),
    ]
