# Generated by Django 5.0.7 on 2025-01-10 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monit_remains', '0004_remain_products_name_1_remain_products_name_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remain',
            name='dose_products_1',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза продукта 1 на одну голову, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='dose_products_2',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза продукта 2 на одну голову, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='dose_products_3',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза продукта 3 на одну голову, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='dose_products_4',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза продукта 4 на одну голову, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='dose_products_5',
            field=models.FloatField(blank=True, null=True, verbose_name='Доза продукта 5 на одну голову, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='number_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов на "1" продукт'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='number_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов на "2" продукт'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='number_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов на "3" продукт'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='number_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов на "4" продукт'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='number_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество голов на "5" продукт'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_1',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 1, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_2',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 2, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_3',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 3, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_4',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 4, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_5',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество продукта 5, кг'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_name_1',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 1'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_name_2',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 2'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_name_3',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 3'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_name_4',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 4'),
        ),
        migrations.AlterField(
            model_name='remain',
            name='products_name_5',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Продукт 5'),
        ),
    ]
