# Generated by Django 5.0.7 on 2024-10-31 06:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultants', '0014_alter_organization_manager'),
        ('user_app', '0014_personalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, null=True, verbose_name='Дата мониторинга')),
                ('foto_1', models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Фото верхнего сита 19 мм')),
                ('foto_2', models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Фото среднего сита 8 мм')),
                ('foto_3', models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Фото нижнего сита 4 мм')),
                ('foto_4', models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Фото поддона')),
                ('feed_mixture', models.TextField(max_length=4000, null=True, verbose_name='Замечания по кормосмеси')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания записи')),
                ('user_name', models.CharField(max_length=100, null=True, verbose_name='ФИО')),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='user_app.job', verbose_name='Должность специалиста')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitoringfeeds', to='consultants.organization', verbose_name='Организация')),
            ],
        ),
    ]
