# Generated by Django 5.0.7 on 2024-11-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringfeed',
            name='feed_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='feed_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='feed_3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='feed_4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='percent_feed_1',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='percent_feed_2',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='percent_feed_3',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='percent_feed_4',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='monitoringfeed',
            name='summa',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='foto_1',
            field=models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Вид(фото) верхнего сита 30 мм'),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='foto_2',
            field=models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Вид(фото) среднего сита 8 мм'),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='foto_3',
            field=models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Вид(фото)нижнего сита 4 мм'),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='foto_4',
            field=models.ImageField(upload_to='foto_monitoring/%Y/%m/%d', verbose_name='Вид(фото) поддона'),
        ),
    ]
