# Generated by Django 5.0.7 on 2024-11-03 07:31

import monitoring.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_monitoringfeed_feed_1_monitoringfeed_feed_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_4',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='percent_feed_1',
            field=models.FloatField(default=0.0, editable=False, validators=[monitoring.models.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='percent_feed_2',
            field=models.FloatField(default=0.0, editable=False, validators=[monitoring.models.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='percent_feed_3',
            field=models.FloatField(default=0.0, editable=False, validators=[monitoring.models.validate_percentage]),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='percent_feed_4',
            field=models.FloatField(default=0.0, editable=False, validators=[monitoring.models.validate_percentage]),
        ),
    ]
