# Generated by Django 5.0.7 on 2024-11-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0004_monitoringfeed_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringfeed',
            name='group',
            field=models.CharField(max_length=100, null=True, verbose_name='Группа животных'),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_1',
            field=models.IntegerField(verbose_name='Количество остатков верхнего сита, гр.'),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_2',
            field=models.IntegerField(verbose_name='Количество остатков среднего сита, гр.'),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_3',
            field=models.IntegerField(verbose_name='Количество остатков нижнего сита, гр.'),
        ),
        migrations.AlterField(
            model_name='monitoringfeed',
            name='feed_4',
            field=models.IntegerField(verbose_name='Количество остатков дна, гр.'),
        ),
    ]
